Fixes for Intel.

diff --git a/opt/regataos-prime/scripts/intel-gpu-frequency b/opt/regataos-prime/scripts/intel-gpu-frequency
--- a/opt/regataos-prime/scripts/intel-gpu-frequency
+++ b/opt/regataos-prime/scripts/intel-gpu-frequency
@@ -2,32 +2,31 @@
 
 cd /
 
-while :
-do
+while :; do
 
-# Capture Intel GPU info
-ps -C regataosprime > /dev/null;
-if [ $? = 0 ] ; then
-	gpu=$(inxi -G | grep Device-1)
-	if [[ $gpu == *"Intel"* ]]; then
-		# Capture the discrete GPU frequency
-		gpu_freq=$(intel_gpu_frequency | grep cur | awk '{print $2}')
-		echo "$gpu_freq" > /tmp/regataos-prime/intel_gpu_freq.log
+	# Capture Intel GPU info
+	ps -C regataosprime >/dev/null
+	if [ $? = 0 ]; then
+		gpu=$(inxi -G | grep Device-1)
+		if [[ $gpu == *"Intel"* ]]; then
+			# Capture the discrete GPU frequency
+			gpu_freq=$(intel_gpu_frequency | grep cur | awk '{print $2}')
+			echo "$gpu_freq" >/tmp/regataos-prime/intel_gpu_freq.log
+		else
+			echo "Intel GPU not found."
+			break
+		fi
 	else
-		echo "Intel GPU not found."
+		if test -e "/tmp/regataos-prime/intel_gpu_freq.log"; then
+			rm -f "/tmp/regataos-prime/intel_gpu_freq.log"
+			rm -f "/tmp/regataos-prime/intel_gpu_top.log"
+		fi
+
+		killall intel_gpu_top
+		killall intel-gpu-usage
+
 		break
 	fi
-else
-	if test -e "/tmp/regataos-prime/intel_gpu_freq.log"; then
-		rm -f "/tmp/regataos-prime/intel_gpu_freq.log"
-		rm -f "/tmp/regataos-prime/intel_gpu_top.log"
-	fi
 
-	killall intel_gpu_top
-	killall intel-gpu-usage
-
-	break
-fi
-
-   sleep 1
+	sleep 1
 done
diff --git a/opt/regataos-prime/scripts/intel-gpu-usage b/opt/regataos-prime/scripts/intel-gpu-usage
--- a/opt/regataos-prime/scripts/intel-gpu-usage
+++ b/opt/regataos-prime/scripts/intel-gpu-usage
@@ -1,32 +1,29 @@
 #!/bin/bash
 
-sleep 5
-
 cd /
 
-while :
-do
+while :; do
 
-# Capture Intel GPU info
-ps -C regataosprime > /dev/null;
-if [ $? = 0 ] ; then
-	gpu=$(inxi -G | grep Device-1)
-	if [[ $gpu == *"Intel"* ]]; then
-		# Capture the discrete GPU usage
-		if test -e "/tmp/regataos-prime/intel_gpu_freq.log"; then
-			ps -C intel_gpu_top > /dev/null;
-			if [ $? = 1 ] ; then
-				intel_gpu_top -o /tmp/regataos-prime/intel_gpu_top.log
+	# Capture Intel GPU info
+	ps -C regataosprime >/dev/null
+	if [ $? = 0 ]; then
+		gpu=$(inxi -G | grep Device-1)
+		if [[ $gpu == *"Intel"* ]]; then
+			# Capture the discrete GPU usage
+			if test -e "/tmp/regataos-prime/intel_gpu_freq.log"; then
+				ps -C intel_gpu_top >/dev/null
+				if [ $? = 1 ]; then
+					intel_gpu_top -o /tmp/regataos-prime/intel_gpu_top.log
+				fi
 			fi
+		else
+			echo "Intel GPU not found."
+			break
 		fi
+
 	else
-		echo "Intel GPU not found."
 		break
 	fi
 
-else
-	break
-fi
-
-   sleep 1
+	sleep 1
 done
