More fixes for UI.

diff --git a/opt/regataos-prime/scripts/settings-options b/opt/regataos-prime/scripts/settings-options
--- a/opt/regataos-prime/scripts/settings-options
+++ b/opt/regataos-prime/scripts/settings-options
@@ -38,33 +38,37 @@ function tearfree() {
 }
 
 # Enable/Disable FreeSync
-function enable_freesync() {
-	screen=$(xrandr --props | grep 'connected primary' | awk '{print $1}')
-	echo "Enabling FreeSync on $screen"
-	DISPLAY=:0 xrandr --output $screen --set "freesync" 1
-	xrandr --output $screen --set "freesync" 1
-	sed -i 's/\(freesync=off\)/freesync=on/' "/tmp/regataos-prime/config/regataos-prime.conf"
+function freesync() {
+	if [[ $(cat /tmp/regataos-prime/config/regataos-prime.conf) == *"freesync=on"* ]]; then
+		screen=$(xrandr --props | grep 'connected primary' | awk '{print $1}')
+		echo "Disabling FreeSync on $screen"
+		DISPLAY=:0 xrandr --output $screen --set "freesync" 0
+		xrandr --output $screen --set "freesync" 0
+		sed -i 's/\(freesync=on\)/freesync=off/' "/tmp/regataos-prime/config/regataos-prime.conf"
 
-	# Show notify on desktop
-	/opt/regataos-prime/scripts/notifications/notify -tearfree-on
-}
+		# Show notify on desktop
+		/opt/regataos-prime/scripts/notifications/notify -tearfree-off
 
-function disable_freesync() {
-	screen=$(xrandr --props | grep 'connected primary' | awk '{print $1}')
-	echo "Disabling FreeSync on $screen"
-	DISPLAY=:0 xrandr --output $screen --set "freesync" 0
-	xrandr --output $screen --set "freesync" 0
-	sed -i 's/\(freesync=on\)/freesync=off/' "/tmp/regataos-prime/config/regataos-prime.conf"
+	elif [[ $(cat /tmp/regataos-prime/config/regataos-prime.conf) == *"freesync=off"* ]]; then
+		screen=$(xrandr --props | grep 'connected primary' | awk '{print $1}')
+		echo "Enabling FreeSync on $screen"
+		DISPLAY=:0 xrandr --output $screen --set "freesync" 1
+		xrandr --output $screen --set "freesync" 1
+		sed -i 's/\(freesync=off\)/freesync=on/' "/tmp/regataos-prime/config/regataos-prime.conf"
 
-	# Show notify on desktop
-	/opt/regataos-prime/scripts/notifications/notify -tearfree-off
+		# Show notify on desktop
+		/opt/regataos-prime/scripts/notifications/notify -tearfree-on
+
+	else
+		echo "Option not found in the file with configuration options."
+	fi
 }
 
 # Configuration option for KWin compositing
 function compositor() {
 	# Check if the "compositor" option is present in the configuration file
 	if [[ $(grep -r "compositor=" "/tmp/regataos-prime/config/regataos-prime.conf") != *"compositor="* ]]; then
-		echo "compositor=on" >> "$HOME/.config/regataos-prime/regataos-prime.conf"
+		echo "compositor=on" >>"$HOME/.config/regataos-prime/regataos-prime.conf"
 		sed -i '/^$/d' "$HOME/.config/regataos-prime/regataos-prime.conf"
 	fi
 
@@ -99,7 +103,7 @@ function compositor() {
 function unlock_widgets() {
 	# Check if the "unlockwidgets" option is present in the configuration file
 	if [[ $(grep -r "unlockwidgets=" "/tmp/regataos-prime/config/regataos-prime.conf") != *"unlockwidgets="* ]]; then
-		echo "unlockwidgets=off" >> "$HOME/.config/regataos-prime/regataos-prime.conf"
+		echo "unlockwidgets=off" >>"$HOME/.config/regataos-prime/regataos-prime.conf"
 		sed -i '/^$/d' "$HOME/.config/regataos-prime/regataos-prime.conf"
 	fi
 
@@ -134,7 +138,7 @@ function unlock_widgets() {
 function configure_amf() {
 	# Check if the "amf" option is present in the configuration file
 	if [[ $(grep -r "amf=" "/tmp/regataos-prime/config/regataos-prime.conf") != *"amf="* ]]; then
-		echo "amf=off" >> "$HOME/.config/regataos-prime/regataos-prime.conf"
+		echo "amf=off" >>"$HOME/.config/regataos-prime/regataos-prime.conf"
 		sed -i '/^$/d' "$HOME/.config/regataos-prime/regataos-prime.conf"
 	fi
 
@@ -175,21 +179,26 @@ function copy_info() {
 }
 
 case $1 in
-   "-tearfree") tearfree
-         ;;
-   "-freesync-on") enable_freesync
-         ;;
-   "-freesync-off") disable_freesync
-         ;;
-   "-compositor") compositor
-         ;;
-   "-unlockwidgets") unlock_widgets
-         ;;
-   "-amf") configure_amf
-         ;;
-   "-copy-info") copy_info
-         ;;
-   *) echo "Invalid option!"
-      exit 1
-      ;;
+"-tearfree")
+	tearfree
+	;;
+"-freesync")
+	freesync
+	;;
+"-compositor")
+	compositor
+	;;
+"-unlockwidgets")
+	unlock_widgets
+	;;
+"-amf")
+	configure_amf
+	;;
+"-copy-info")
+	copy_info
+	;;
+*)
+	echo "Invalid option!"
+	exit 1
+	;;
 esac
